sonar.projectKey=obe-app
sonar.projectName=obe-app
sonar.projectVersion=1.2

sonar.sources=app,routes
sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/**,database/**

# khusus matikan deteksi duplicated code untuk file yang bikin gate gagal
sonar.cpd.exclusions=app/Http/Controllers/ClassroomController.php

sonar.sourceEncoding=UTF-8