sonar.projectKey=obe-app
sonar.projectName=obe-app
sonar.projectVersion=1.1

sonar.sources=app,routes
sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/**,database/**

sonar.sourceEncoding=UTF-8